module.exports = {
  purge: { content: ["./public/**/*.html", "./src/**/*.vue"] },
  darkMode: false, // or 'media' or 'class'
  theme: {
    colors: {
      white: "#fff",
      transparent: "transparent",
      black: "#000",
      blackPanther: "#414141",
      americanSilver: "#cecece",
      lightPurple: "#7349ac",
      darkPurple: "#512888",
      lunarRock: "#C5C5C5",
      speedOfLight: "#F6F4F0",
      irishGreen: "#25A131",
      unicornSilver: "#e7e7e7",
      lead: "#202121",
      blue: "#2B6FC0",
      lightOrange: "#ec6123",
      darkOrange: "#d94201",
      scarabaeusSacer: "#404040",
      strongEnvy: "#742727",
      sepiaRose: "#D4B8B5",
      whiteSmoke: "#F5F6F7",
      miyamotoRed: "#E10C0C",
      vampireStateBuilding: "#CC0E00",
      pamperedPrincess: "#F3EAEA",
      lavaPit: "#E17132",
      wildPrimrose: "#F2E19D",
      mountainMint: "#AAE3C0",
      loveSpell: "#FAB6C4",
      purpleIllusion: "#B2BBFA",
      coralBisque: "#FAC9B5",
      superSilver: "#EFEFEF",
    },
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
